### ISSUE TITLE
Theme Colors

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/blissfulbuttons#3]
Now it looks good in the editor but whenever I pick one of the four presents colors it shows up on the backend but not on the front end. Likely because it doesn’t add it inline like when you add a custom color but rather it adds a different class like
.has-secondary-color

For each one you have the color and background color set. Is that necessary? If removed than the other classes will fill in the colors.

**Comment by nickhamze** [comment]
Hmm, the hover states are messed up as well if it uses their alternate classes (.has-secondary-color). They change the color on hover but we don't as we rely an animation instead. But since we don't set a hover background and color it just inherits the theme one which looks bad. 

Is there any way to disable them and make it put all the code inline? I thought this was going to be easy but it's surprisingly complex.

**Comment by Mamaduka** [comment]
@nickhamze I don't think it's currently possible to fix color palette issue with Go theme. Disabling theme color palette isn't plugin/block territory.

**Comment by nickhamze** [comment]
Ok, let's put this on hold for a day or two. I'm going to play around with it a bit.
